"""
Hebrew Glyph Declarations — Phase 2B-I

All glyphs are inert structural forms.
No phonetics, semantics, or behavior is defined.
"""

HEBREW_GLYPHS = {
    "ALEPH": {
        "id": "HEB_ALEPH",
        "stroke_count": 3,
        "stroke_types": {"line", "angle"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"top", "bottom"},
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
    "BET": {
        "id": "HEB_BET",
        "stroke_count": 3,
        "stroke_types": {"line", "angle"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"left"},
        "closedness": "partial",
        "interior_space": "bounded",
        "planarity": "2D",
    },
    "GIMEL": {
        "id": "HEB_GIMEL",
        "stroke_count": 2,
        "stroke_types": {"line", "angle"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"bottom"},
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
    "DALET": {
        "id": "HEB_DALET",
        "stroke_count": 2,
        "stroke_types": {"line", "angle"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"right"},
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
    "HE": {
        "id": "HEB_HE",
        "stroke_count": 3,
        "stroke_types": {"line"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"left", "top"},
        "closedness": "partial",
        "interior_space": "bounded",
        "planarity": "2D",
    },
    "VAV": {
        "id": "HEB_VAV",
        "stroke_count": 1,
        "stroke_types": {"line"},
        "symmetry": "bilateral",
        "orientation": "fixed",
        "attachment_faces": {"top", "bottom"},
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
    "ZAYIN": {
        "id": "HEB_ZAYIN",
        "stroke_count": 2,
        "stroke_types": {"line"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"top"},
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
    "HET": {
        "id": "HEB_HET",
        "stroke_count": 3,
        "stroke_types": {"line"},
        "symmetry": "bilateral",
        "orientation": "fixed",
        "attachment_faces": {"left", "right"},
        "closedness": "partial",
        "interior_space": "bounded",
        "planarity": "2D",
    },
    "TET": {
        "id": "HEB_TET",
        "stroke_count": 4,
        "stroke_types": {"curve", "line"},
        "symmetry": "radial",
        "orientation": "fixed",
        "attachment_faces": set(),
        "closedness": "closed",
        "interior_space": "bounded",
        "planarity": "2D",
    },
    "YOD": {
        "id": "HEB_YOD",
        "stroke_count": 1,
        "stroke_types": {"point"},
        "symmetry": "radial",
        "orientation": "fixed",
        "attachment_faces": set(),
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
    "KAF": {
        "id": "HEB_KAF",
        "stroke_count": 2,
        "stroke_types": {"curve"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"right"},
        "closedness": "partial",
        "interior_space": "bounded",
        "planarity": "2D",
    },
    "LAMED": {
        "id": "HEB_LAMED",
        "stroke_count": 2,
        "stroke_types": {"line", "curve"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"top"},
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
    "MEM": {
        "id": "HEB_MEM",
        "stroke_count": 4,
        "stroke_types": {"line"},
        "symmetry": "bilateral",
        "orientation": "fixed",
        "attachment_faces": set(),
        "closedness": "closed",
        "interior_space": "bounded",
        "planarity": "2D",
    },
    "NUN": {
        "id": "HEB_NUN",
        "stroke_count": 2,
        "stroke_types": {"line"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"bottom"},
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
    "SAMEKH": {
        "id": "HEB_SAMEKH",
        "stroke_count": 1,
        "stroke_types": {"curve"},
        "symmetry": "radial",
        "orientation": "fixed",
        "attachment_faces": set(),
        "closedness": "closed",
        "interior_space": "bounded",
        "planarity": "2D",
    },
    "AYIN": {
        "id": "HEB_AYIN",
        "stroke_count": 2,
        "stroke_types": {"line"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"bottom"},
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
    "PE": {
        "id": "HEB_PE",
        "stroke_count": 3,
        "stroke_types": {"curve", "line"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"left"},
        "closedness": "partial",
        "interior_space": "bounded",
        "planarity": "2D",
    },
    "TSADI": {
        "id": "HEB_TSADI",
        "stroke_count": 3,
        "stroke_types": {"line"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"bottom"},
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
    "QOF": {
        "id": "HEB_QOF",
        "stroke_count": 3,
        "stroke_types": {"curve", "line"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"bottom"},
        "closedness": "partial",
        "interior_space": "bounded",
        "planarity": "2D",
    },
    "RESH": {
        "id": "HEB_RESH",
        "stroke_count": 2,
        "stroke_types": {"curve"},
        "symmetry": "none",
        "orientation": "fixed",
        "attachment_faces": {"right"},
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
    "SHIN": {
        "id": "HEB_SHIN",
        "stroke_count": 3,
        "stroke_types": {"line"},
        "symmetry": "bilateral",
        "orientation": "fixed",
        "attachment_faces": {"bottom"},
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
    "TAV": {
        "id": "HEB_TAV",
        "stroke_count": 2,
        "stroke_types": {"line"},
        "symmetry": "bilateral",
        "orientation": "fixed",
        "attachment_faces": {"top"},
        "closedness": "open",
        "interior_space": "none",
        "planarity": "2D",
    },
}
